### ISSUE TITLE
[frost-coordinator] random dkg_round_id values

### ISSUE THREAD

**Issue by donpdonp** [Trust-Machines/core-eng#43]
- change dkg_id to dkg_round_id
- dkg_round_id is a u64 and currently the coordinator starts with the same value. If the coordinator is started and stopped, it sends out a new DKG_BEGIN with the same value and confuses the signers. 
- One fix for this that would support any reasonable number of non-coordinating coordinators  is to pick a dkg_round_id at random

Alpha: serially increment by coordinator.

**Comment by xoloki** [comment]
I think round IDs should be sequential, otherwise you won't be able to tell where you are in the sequence, how many you missed, etc.  I think signers should refuse to redo a round that's already completed.  

It seems like we're trying to paper over the problem of lack of persistence.  We should just fix that instead.

**Comment by igorsyl** [comment]
In this case, could we consider a time uuid?
https://stackoverflow.com/questions/17945677/cassandra-uuid-vs-timeuuid-benefits-and-disadvantages

**Comment by donpdonp** [comment]
existing setup of a single coordinator using incremental IDs is enough for alpha
