### ISSUE TITLE
Investigate accesible alternatives to peg wire format

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/core-eng#63]
Started issue to track work on this proposal.

[sBTC proposal: Using OP_DROP instead of OP_Return](https://docs.google.com/document/d/1EnYEk6gA2w6VfRpT8CcK8mghZRMUEjn2OhHwzdK_9x0/edit)

**Comment by tycho1212** [comment]
So @FriendsFerdinand tried the OP_DROP prototype out on Bitcoin mainnet, and it works. The OP_DROP transaction gets mined contrary to what some people thought during the sBTC Engineering sync on Monday 13th February

The commit Tx: https://mempool.space/tx/759db869a6491146d99bf54dc1419570c43cd5f09ff6916872ad075f47b64fe1

The unlocking (scriptsig) TX : https://mempool.space/tx/5a148fe2486b667e1e2438bea6a213c7e31ad0c8ce69c45d98bb384da33d8be5

**Comment by igorsyl** [comment]
FYI @jcnelson

**Comment by jcnelson** [comment]
@tycho1212 Yup, that pattern of commit/reveal was expected to work.  Bitcoin is pretty liberal in what it will accept in a scriptSig.

My concern from the call was that putting `OP_PUSHBYTES20 ... OP_DROP OP_DUP OP_HASH160 ... OP_EQUALVERIFY OP_CHECKSIG` in the _scriptPubKey_ was not a standard transaction on mainnet.  And, that's not what was mined here.

**Comment by jcnelson** [comment]
Indeed, if you look at the Bitcoin source code, you'll see in the `Solver()` function in `src/script/standard.cpp` that this particular operation pattern would evaluate to `TxoutType::NONSTANDRARD`, because it's not a p2sh scriptPubKey, it's not a witness program, it's not an `OP_RETURN` payload, it's not a pay-to-pubkey program, it's not a pay-to-pubkey-hash program, and it's not a multisig program.

However, if you look at `IsStandardTx()` in `src/policy/policy.cpp`, you'll see that the only rules for the scriptSigs are that:

* the size of a scriptSig is no bigger than `MAX_STANDARD_SCRIPTSIG_SIZE` bytes, or 1,650 bytes
* each opcode besides data is a data push opcode (handled by `IsPushOnly()` in `src/script/script.cpp`).

The lesson here is to only do exotic things in the scriptSig or witness stack.  The set of valid scriptPubKey programs is very constrained.

**Comment by tycho1212** [comment]
@jcnelson thanks for clarifying where the misunderstanding on the call on Monday came from. Happy to have that cleared up.

Let's discuss next steps on the call later today
